name: CI

on:
  push:
    branches: [ main, fix/1-codestyle ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8
        run: |
          flake8 shopping_cart.py

      - name: Run unit tests
        run: |
          python -m unittest discover -s . -p "test_*.py"
